version: '3'
services:
  db:
    container_name: db
    image: mysql:5.7
    ports:
    - 3306:3306
    restart: always
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/my.cnf
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:5.0
    # platform: linux/arm64
    restart: always
    network_mode: bridge
    environment:
      PMA_HOST: 172.17.0.1:3306
    ports:
      - 8183:80    